#############################################################################
# Makefile for building: sslserver.app/Contents/MacOS/sslserver
# Generated by qmake (3.0) (Qt 5.1.0) on: Wed Jul 17 19:29:46 2013
# Project:  sslserver.pro
# Template: app
# Command: /Users/edu/Qt5.1.0/5.1.0/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile sslserver.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -Woverloaded-virtual -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/macx-clang -I. -I. -I../../../../Qt5.1.0/5.1.0/clang_64/include -I../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork -I../../../../Qt5.1.0/5.1.0/clang_64/lib/QtNetwork.framework/Headers -I../../../../Qt5.1.0/5.1.0/clang_64/include/QtGui -I../../../../Qt5.1.0/5.1.0/clang_64/lib/QtGui.framework/Headers -I../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore -I../../../../Qt5.1.0/5.1.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/edu/Qt5.1.0//5.1.0/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/edu/Qt5.1.0//5.1.0/clang_64/lib -framework QtNetwork -F/Users/edu/Qt5.1.0//5.1.0/clang_64/qtbase/lib -framework QtCore -framework QtGui -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/edu/Qt5.1.0/5.1.0/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		sslserver.cpp moc_sslserver.cpp
OBJECTS       = main.o \
		sslserver.o \
		moc_sslserver.o
DIST          = ../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/default_pre.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/declarative_debug.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/lex.prf \
		sslserver.pro \
		sslserver.pro
QMAKE_TARGET  = sslserver
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = sslserver.app/Contents/MacOS/sslserver

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile sslserver.app/Contents/PkgInfo sslserver.app/Contents/Resources/empty.lproj sslserver.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d sslserver.app/Contents/MacOS/ || mkdir -p sslserver.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sslserver.pro ../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/default_pre.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/declarative_debug.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/lex.prf \
		sslserver.pro \
		/Users/edu/Qt5.1.0/5.1.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/edu/Qt5.1.0/5.1.0/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/edu/Qt5.1.0/5.1.0/clang_64/lib/QtGui.framework/QtGui.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile sslserver.pro
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/qdevice.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/device_config.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/unix.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/mac.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/macx.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/clang.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/qconfig.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_bootstrap.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_clucene.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_v8.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/spec_post.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/default_pre.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/default_post.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/declarative_debug.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/qt.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/resources.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/moc.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/yacc.prf:
../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/features/lex.prf:
sslserver.pro:
/Users/edu/Qt5.1.0/5.1.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/edu/Qt5.1.0/5.1.0/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/edu/Qt5.1.0/5.1.0/clang_64/lib/QtGui.framework/QtGui.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile sslserver.pro

qmake_all: FORCE

sslserver.app/Contents/PkgInfo: 
	@test -d sslserver.app/Contents || mkdir -p sslserver.app/Contents
	@$(DEL_FILE) sslserver.app/Contents/PkgInfo
	@echo "APPL????" >sslserver.app/Contents/PkgInfo
sslserver.app/Contents/Resources/empty.lproj: 
	@test -d sslserver.app/Contents/Resources || mkdir -p sslserver.app/Contents/Resources
	@touch sslserver.app/Contents/Resources/empty.lproj
	
sslserver.app/Contents/Info.plist: 
	@test -d sslserver.app/Contents || mkdir -p sslserver.app/Contents
	@$(DEL_FILE) sslserver.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,sslserver,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt5.1.0/5.1.0/clang_64/mkspecs/macx-clang/Info.plist.app >sslserver.app/Contents/Info.plist
dist: 
	@test -d .tmp/sslserver1.0.0 || mkdir -p .tmp/sslserver1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sslserver1.0.0/ && $(COPY_FILE) --parents sslserver.h .tmp/sslserver1.0.0/ && $(COPY_FILE) --parents main.cpp sslserver.cpp .tmp/sslserver1.0.0/ && (cd `dirname .tmp/sslserver1.0.0` && $(TAR) sslserver1.0.0.tar sslserver1.0.0 && $(COMPRESS) sslserver1.0.0.tar) && $(MOVE) `dirname .tmp/sslserver1.0.0`/sslserver1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sslserver1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r sslserver.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_sslserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sslserver.cpp
moc_sslserver.cpp: ../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/QTcpServer \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qtcpserver.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobject.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobjectdefs.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qnamespace.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qglobal.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qconfig.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qfeatures.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsystemdetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qprocessordetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qglobalstatic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qbasicatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qgenericatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_power.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_mips.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_s390.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_x86.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_unix.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmutex.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlogging.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qflags.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtypeinfo.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtypetraits.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsysinfo.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qstring.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qchar.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qbytearray.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qrefcount.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qarraydata.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qstringbuilder.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlist.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qalgorithms.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qiterator.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcoreevent.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qscopedpointer.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmetatype.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qisenum.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobject_impl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qabstractsocket.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qiodevice.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qdebug.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qhash.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qpair.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmap.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtextstream.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlocale.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvariant.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qshareddata.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvector.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qpoint.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qset.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qhostaddress.h \
		sslserver.h
	/Users/edu/Qt5.1.0//5.1.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) sslserver.h -o moc_sslserver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/QCoreApplication \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcoreapplication.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qglobal.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qconfig.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qfeatures.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsystemdetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qprocessordetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qglobalstatic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qbasicatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qgenericatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_power.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_mips.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_s390.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_x86.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_unix.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmutex.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlogging.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qflags.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtypeinfo.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtypetraits.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsysinfo.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qstring.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qchar.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qbytearray.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qrefcount.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qnamespace.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qarraydata.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qstringbuilder.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobject.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobjectdefs.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlist.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qalgorithms.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qiterator.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcoreevent.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qscopedpointer.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmetatype.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qisenum.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobject_impl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qeventloop.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/QFile \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qfile.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qfiledevice.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qiodevice.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/QDebug \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qdebug.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qhash.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qpair.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmap.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtextstream.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlocale.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvariant.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qshareddata.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvector.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qpoint.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qset.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/QSslCertificate \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qsslcertificate.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcryptographichash.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qdatetime.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsharedpointer.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qregexp.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qssl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/QFlags \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/QSslKey \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qsslkey.h \
		sslserver.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/QTcpServer \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qtcpserver.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qabstractsocket.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

sslserver.o: sslserver.cpp ../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/QSslCertificate \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qsslcertificate.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qnamespace.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qglobal.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qconfig.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qfeatures.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsystemdetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qprocessordetection.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qglobalstatic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qbasicatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qgenericatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_power.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_mips.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_s390.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_x86.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qatomic_unix.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmutex.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlogging.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qflags.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtypeinfo.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtypetraits.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsysinfo.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qbytearray.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qrefcount.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qarraydata.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qstring.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qchar.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qstringbuilder.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcryptographichash.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qdatetime.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsharedpointer.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qshareddata.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobject.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobjectdefs.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlist.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qalgorithms.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qiterator.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcoreevent.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qscopedpointer.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmetatype.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qisenum.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qobject_impl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qhash.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qpair.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qregexp.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qmap.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qdebug.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qtextstream.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qiodevice.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qlocale.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvariant.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qvector.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qpoint.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qset.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qssl.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/QFlags \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/QSslKey \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qsslkey.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/QSslSocket \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qsslsocket.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qtcpsocket.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qabstractsocket.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qsslerror.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/QStringList \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qstringlist.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qdatastream.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtCore/qstringmatcher.h \
		sslserver.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/QTcpServer \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qtcpserver.h \
		../../../../Qt5.1.0/5.1.0/clang_64/include/QtNetwork/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sslserver.o sslserver.cpp

moc_sslserver.o: moc_sslserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sslserver.o moc_sslserver.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

